language: android
dist: trusty
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The SDK version used to compile your project
    - android-28

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository
before script:
    - echo "starting travis script"
    - echo "Travis branch is $TRAVIS_BRANCH"
    - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
script: ./gradlew test
